name: CI

on: [pull_request]

jobs:

  test:
    runs-on: macos-13
    steps:
        - uses: actions/checkout@v4

        - name: Select Xcode
          run: sudo xcode-select -s "/Applications/Xcode_15.0.1.app"

        - name: CocoaPods
          run: pod install

        - name: Xcode UnitTest
          run: xcodebuild test -workspace univIP.xcworkspace -scheme univIP -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14" -skip-testing:univIPUITests
