name: CI

on: [push]

# 動作バージョンの指定
env:
 DEVELOPER_DIR: /Applications/Xcode_15.0.app

jobs:
  build:
    runs-on: macos-13

    steps:
    # チェックアウト
    - uses: actions/checkout@v3

    # CocoaPodsをインストールする
    - name: CocoaPods
      run: pod install

    # ビルド
    - name: Xcode build
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -workspace univIP.xcworkspace
        -scheme univIP-test
        build

    # 単体テストの実行
    - name: Xcode test
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -workspace univIP.xcworkspace
        -scheme univIP
        -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max'
        -skip-testing:univIPUITests
        clean test

  info:
    runs-on: macos-13

    steps:
    # Xcodeの一覧出力
    - name: Show Xcode list
      run: ls /Applications | grep 'Xcode'

    # Xcodeのバージョン出力
    - name: Show Xcode version
      run: xcodebuild -version
